# Generated by Django 3.2.5 on 2021-07-08 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travello', '0002_remove_destination_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='destination',
            name='price',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
